# Generated by Django 3.2.8 on 2021-10-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
