# Generated by Django 3.2.8 on 2021-10-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_manager', '0002_alter_image_post_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Photos',
        ),
    ]
